apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tipbot-slack
  labels:
    app: tipbot-slack
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tipbot-slack
        revision: __REVISION__
    spec:
      containers:
      - name: hello-app
        image: gcr.io/mobius-network/hello-app:__REVISION__
        imagePullPolicy: Always
        command: "bundle exec ruby slack.rb"
